### ISSUE TITLE
README.md simplifying

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#10]
I have a suggestion for simplifying the "README.md":

Make a script for example "Dreamer.sh" and put

rm -rf meta-dream
git clone -b test1 https://github.com/DMM-PLi/meta-dream.git
rm -f meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend
rm -f meta-openpli/recipes-filesystems/smbnetfs/smbnetfs_git.bbappend
cp -R meta-dream/recipes-daemons/vsftpd/ meta-openpli/recipes-daemons/
cp -f meta-dream/recipes-connectivity/samba/samba_4.6.%.bbappend meta-openpli/recipes-connectivity/samba/samba_4.%.bbappend
cp -f meta-dream/recipes-connectivity/inadyn-mt/inadyn-mt.bb meta-openpli/recipes-connectivity/inadyn-mt/inadyn-mt.bb

in it then using sed to do the line edits and put them in "Dreamer.sh" again ...

After this we just need to do "sh Dreamer.sh" in a terminal.

**Comment by Hains** [comment]
Sounds good.

But i'm not familiar with using 

also  bitrate.bb and autobouwetsmaker.bb are not present after git clone openpli as they are in submodule.
So in that case i have to add the recipes to meta-dream and also copy to meta-openpli.
No problem , i will do that.

iperf in openpli-feed, can probably be done with a bbappend, like  we do with
dvb-apps, thus remove iperf from feed and add iperf3.

Only enigma2.bb left, can try to use bbappend, and see if it works?

**Comment by Hains** [comment]
Done for bitrate and autobouqetsmaker.

Now we have half openpli-oe-core in meta-dream :)

**Comment by persianpros** [comment]
No problem I will make the "Dreamer.sh" soon then we'll be able to do the edits with just 1 terminal command :)

Can't we use bbappend for submodules too?

Please suggest this to PLi's members:

- Remove dm8000 and all dreambox related files
- Point meta-dream to us or just leave it alone with a simple link for devs

**Comment by Hains** [comment]
bbappends are problem. I never succeed with them. 'inherit' must be done in a specific order.
With bbappends it doesn't work.

But i see another problem with last commits..i fix it.

**Comment by Hains** [comment]
First test1 branch openpli must be ready for new OE-core.
So we don't need to edit, copy and remove a bunch of files.
Only openwebif.bbappend.

**Comment by persianpros** [comment]
Now we have a new repo: https://github.com/DMM-PLi/Dreamer
;)

**Comment by Hains** [comment]
:)

Better.
