### ISSUE TITLE
Dm7080 error

### ISSUE THREAD

**Issue by audi06** [DMM-PLi/meta-dream#15]
branch rocko
dm9x0 ok
dm820 ok
dm520 ok
dm7080 error
http://opendreambox.dreamosat.net/index.php?action=downloadfile&filename=log.do_compile.15645&directory=OpenPLi%206.0%20(branch%20rocko)/log&

**Comment by Hains** [comment]
Try:
https://github.com/DMM-PLi/meta-dream/commit/46a3aeceb93803d5df86015d9ee2a8379011bb90

Not tested yet.

**Comment by audi06** [comment]
dreamosat@debian:~/Genel/OpenPLi-DM/openpli-oe-core$ cd meta-dream && git pull origin rocko && cd ..
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/DMM-PLi/meta-dream
 * branch            rocko      -> FETCH_HEAD
   3c160ba..46a3aec  rocko      -> origin/rocko
Updating 3c160ba..46a3aec
Fast-forward
 .../enigma2/enigma2/dual-tuner-letter-detection-dm7080.patch            | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
dreamosat@debian:~/Genel/OpenPLi-DM/openpli-oe-core$

http://opendreambox.dreamosat.net/files/OpenPLi 6.0 (branch rocko)/.log/log.do_compile.31138

**Comment by Hains** [comment]
Ok i see problem.

I start build dm7080 myself and test. I'll back in a couple of hours.

**Comment by audi06** [comment]
dm900
ftp problem specified, no problem
ftp ok
telnet ok

**Comment by Hains** [comment]
Thanks for reporting, yes member Freon at openpli forum has a local problem.
I have revert the patch.

Build dm7080 ready in +/- 30 minutes. If i'm right about problem, i can fix it in a few minutes
I'm still in the 'C language' mode :) .

**Comment by Hains** [comment]
https://github.com/DMM-PLi/meta-dream/commit/c50b27371316ac02e9f3075bb0d01f1e80bb20c5

**Comment by audi06** [comment]
Thank you
branch rocko
dm7080 build ok

http://opendreambox.dreamosat.net/index.php?&direction=1&order=nom&directory=OpenPLi%206.0%20(branch%20rocko)/dm7080

**Comment by Hains** [comment]
Can you test skin_display with dm900? It's at default in image now.
There are some differents between OpenATV and OpenPLi in code how to handle with skin_display.
But it seems adding skin_display_dm900 is sufficient in OpenPLi(just like vusolo4k).
