### ISSUE TITLE
Status report

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#16]
Since https://github.com/DMM-PLi/meta-dream/issues/5 has more than hundred replies I did close it so we can talk in a fresh one ;)

Should we add "python-service-identity" to all images?
I mean instead of https://github.com/MastaG/pli-oe-core/commit/51940dd7a6ba21cec8fd9c45c56b4dde1a6e8b31 do it here: https://github.com/DMM-PLi/meta-dream/blob/develop/recipes-openpli/enigma2/enigma2.bbappend

**Comment by Hains** [comment]
Yes perhaps it's better to add it to enigma2.bbappend in meta-dream.
When we switch from MastaG to OpenPLi github repo  it's already done.

**Comment by persianpros** [comment]
Will PLi accept our changes? I don't think so ...

Also https://github.com/Hains/meta-dream is very old you can safely remove it ;)

**Comment by Hains** [comment]
The enigma2 patches..now way.. but python-service_identity is a ok i think.

Yes my meta-dream is old..i will remove it.No need for that.

**Comment by persianpros** [comment]
Also I have a question about updating a submodule, What's the best and fast way to do it?
I mean for "meta-raspberrypi" in https://github.com/MastaG/pli-oe-core

**Comment by Hains** [comment]
cd meta-rasberrypi
git pull origin master         (or other branch you use)
cd ..
git add meta-rasberrypi
git commit
git push

**Comment by persianpros** [comment]
Yeah I know about this but is there a way that we can do it online on github like what we do with merge requests? So I can do it without git

**Comment by Hains** [comment]
Ah via webinterface..Sorry i don't know(if it's possibble BTW?).

**Comment by persianpros** [comment]
I did commit some our patches to PLi's enigma2 and now we have to remove them:
https://github.com/OpenPLi/enigma2/commit/543c9ad8034c4300f35b5a61bc9b9e3f92f1f32b
https://github.com/OpenPLi/enigma2/commit/72025176c0f8fbeec851058225e06dd30754dbf2

**Comment by Hains** [comment]
Great, the less patches, the better. I remove them(or would you do it?).

**Comment by persianpros** [comment]
Please do it as I don't have access to a linux pc for next 2 days ...
Thanks in advance.

**Comment by persianpros** [comment]
I think you need to consider skin patch only for dm900/dm920 not all, I try to commit global/universal patches directly to PLi's enigma2 always :)

**Comment by Hains** [comment]
Done.
What about the other try to fix snr patch
https://github.com/DMM-PLi/meta-dream/commit/2a970c62d169139207756d2c4731f434fc3a66ad

**Comment by Hains** [comment]
Meta-dream now with correct commits. You can check it.
Can you make pull request for dm900/920 skin to OpenPLi in the future? That's what you mean right?
I think they are not happy.

**Comment by persianpros** [comment]
Your snr fix for later as PLi won't accept so many changes at once, I'll try for it and let you know.

They won't accept skin changes for dm9x0 like never so we have to keep it here but it has to apply only for dm9x0 not the rest, I will fix it don't worry.

**Comment by Hains** [comment]
Ok. Thanks.
One problem left dm900:
-configuration triple tuner.
But i need to ask @El Sato at OpenPLi forum, what exactly is the problem?
Then we know more.

**Comment by audi06** [comment]
branch rocko
dm900
image flash install FTP port:21 error
image barr allen install FTP port:21 ok

**Comment by audi06** [comment]
@Hains 
dm900 
LCD screen last change enough, more personal preference

**Comment by Hains** [comment]
Can you remember the error?

Now i'm really confused.
User El Sato at forum forum has no problem
There was indeed a problem with ftp but i reverted that commit on saturday.
https://github.com/MastaG/pli-oe-core/commit/d2f82d1c0a0e11658f37720db1843784b51f67a1

Froen reported error: libcripto is missing... 
But he's the only one.

User Adga has download an image, i assume it's yours, and he has no problem with FTP.

Is you pli-oe-core still up to date?
If so, i will add chroot patch again with all config files. I use the patch and config files on my dm8000 and FTP is working fine, I use FileZilla BTW.

You can also use port 22(sftp-ssh). Be keep in mind, you have to set an password with telnet command 'passwd' first.

**Comment by MastaG** [comment]
libcrypto/libssl comes up missing when they try and run CCcam or other closed-source cams..
They require a very old (0.97 or 0.98) version.. which isn't built  anymore.
I tell them to use oscam instead.

**Comment by Hains** [comment]
So i assume FTP works for them?, dm900 is ARM box, so they had to use OScam anyway

**Comment by audi06** [comment]
@Hains 
I have reported an FTP error on complaints from users
I installed myself flash no problem FTP port21 active
http://opendreambox.dreamosat.net/index.php?&direction=1&order=nom&directory=OpenPLi%206.0%20(branch%20rocko)

**Comment by audi06** [comment]
dreamosat@debian:~$ ssh -p 22 root@dm900.fritz.box
The authenticity of host 'dm900.fritz.box (192.168.178.21)' can't be established.
RSA key fingerprint is 38:06:b1:9b:13:7f:2d:83:9b:28:b0:d9:fb:ac:83:f7.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'dm900.fritz.box,192.168.178.21' (RSA) to the list of known hosts.
root@dm900.fritz.box's password: 
root@dm900:~#

**Comment by Hains** [comment]
So FTP is ok. Users has old image or need to re-install vsftpd.

**Comment by audi06** [comment]
I told the users the latest version of the installs.

**Comment by Hains** [comment]
Flash new (working) image. or if you can change opkg files via sftp-ssh or samba or whatever, they can reinstall vsftp. otherwise they have to flash.

Users are aware, this is a TEST? There are still things which doesn't work.
You need to keep pli-oe-core and meta-dream always up to date.
Some things can break in the image(like now with vsftp), so user must be aware of it.

**Comment by persianpros** [comment]
Some enigma2 patches are not present in pyro and develop branch and we have them only in rocko so please add them in pyro and develop too.

I'm on android and it's hard for me to do it now ...

**Comment by persianpros** [comment]
Ok I found another required patch for "BCM45208" tuner: https://github.com/OpenPLi/enigma2/pull/1161/commits/c78922524533357a844390824bcfca680c477d8d
It means https://github.com/OpenPLi/enigma2/commit/543c9ad8034c4300f35b5a61bc9b9e3f92f1f32b is not enough, I'm waiting for PLi's opinion on my merge request and I hope they merge it as it's not box related.

**Comment by Hains** [comment]
Good job:)

snr  Si2169C was solved with this commit only btw:
https://github.com/OpenPLi/enigma2/pull/1161/commits/0a0f51b087fc09c27fd94895a3c1e10afa7ddc12

Now hope openpli accept your PR.

**Comment by persianpros** [comment]
PLi accepted my changes, Now you can remove "tryfix-snr-si216x-tuners.patch" from all 3 branches ;)

**Comment by Hains** [comment]
Done.

**Comment by Hains** [comment]
BTW
https://github.com/OpenPLi/enigma2/commit/d848364e85bcb0080327182e905fd61e4af932b8

There is a parenthesis missing at the end of line 179 of frontend.cpp. 
```
git/lib/dvb/frontend.cpp:1080:2: error: expected ';' before '{' token
```

**Comment by Hains** [comment]
Ah, it's already solved by @Athoik,
https://github.com/OpenPLi/enigma2/commit/55c69deb67fa3ef2a5dd817203f1f109bd1ec186

**Comment by audi06** [comment]
videomode problem, please add it here
Branch rocko error :(
https://github.com/MastaG/pli-oe-core

OpenPLi devolop branch no problem :+1: 
https://github.com/OpenPLi/enigma2/commit/72025176c0f8fbeec851058225e06dd30754dbf2

**Comment by persianpros** [comment]
There's no need for it as a patch, It's in PLi's enigma2 now.
Just compile a new image with new enigma2 ;)

**Comment by audi06** [comment]
I know I do not need a patch
I compiled the new image, error in the top message

**Comment by Hains** [comment]
What error?

**Comment by audi06** [comment]
meaningless error
http://i63.tinypic.com/35ic10n.jpg

**Comment by MastaG** [comment]
no.. it's because I fork PLi's enigma2.. 
I have some small patches applied for my own.. like for example support for BlackHole skins.. minor stuff.
I've just merged PLi's enigma2 into my own.. so all PR's are in now :)
@audi06
Simply make update, and rebuild

**Comment by Hains** [comment]
Ah i see, you have override url with bbappend. pfffff,,
Totally overlooked that.

**Comment by persianpros** [comment]
MastaG's rocko is not official as you can see in https://github.com/MastaG/pli-oe-core/blob/rocko/meta-openpli/recipes-openpli/enigma2/enigma2.bbappend so don't expect PLi's pure enigma2.
Use only develop and pyro branches for PLi otherwise you have to wait for new commits to be merged in MastaG's fork.
I don't get it why testers are using rocko instead of pyro even when we know next PLi's develop will be pyro ...

**Comment by audi06** [comment]
@MastaG  thank you
branch reset 6334 update :)
everything is added again

**Comment by MastaG** [comment]
yeah.. I was busy for the past days so I couldn't really keep up with everything.
Erik is busy preparing the official openpli-oe-core pyro branch, which will be used for the next official PLi release (7.0 I guess).
So soon he'll merge pyro into develop.
Then I'll make a nice PR against PLi's new (pyro) develop with some cherry-picks from my own pli-oe-core (only minor stuff).

So I guess it's best to use the official openpli-oe-core as my pli-oe-core uses my own forked enigma2 (because I like some small unofficial things..)

My pli-oe-core should only be used when people would like to play with OE rocko (the latest and greatest which isn't stable yet..), because I have all the gcc 7 patches in place.
However feature-wise rocko doesn't add anything useful..

**Comment by persianpros** [comment]
I think we need to merge pyro into develop and remove the pyro from our branches then you can keep develop and rocko but no need for "release-6.0/rc" as dreambox is under development and develop branch is enough for it :)

**Comment by Hains** [comment]
No do oot merge, develop is missing some commits regarding dm7080 and dm8000. I cherry-pick them into develop, no problem. if you merge, you have more work to do.

**Comment by persianpros** [comment]
Ok so after your cherry-picks please remove "pyro" branch :)

**Comment by Hains** [comment]
I'ill delete release-6.0. branch .And pyro when done. Also some commits of MastaG are missing in develop.

**Comment by Hains** [comment]
MastaG need to cherry-pick his commits into develop. A lot of commits are not need anymore. Just merge pyro into develop will make a mess. Just as in rocko branch which is a mess now, due to libarchive. Kodi also broken again due to update to 17.5.

**Comment by audi06** [comment]
branch rocko 
build opkg error

[log.do_configure.16830.txt](https://github.com/DMM-PLi/meta-dream/files/1553123/log.do_configure.16830.txt)

**Comment by MastaG** [comment]
yeah.. the libarchive stuff needed to be merged into meta-dream's rocko branch and only for dm800.. as the bug only affects the old kernel (probably some missing syscall) and it's cosmetic only..

I'm only building from my own pyro branch atm, and I merged PLi's pyro branch a few days ago.
develop hasn't been touched in a while.

I need to do some heavy cleaning.
Also the current meta-raspberry submodule revision has another bbappend for openpli-enigma2-image which pulls in extra packages like "lirc"..
Perhaps this is already fixed in the raspberry layer.. perhaps not.. in that case the bbappend's need something like _append_MACHINENAME or something.

I hope to do some cleaning in the following days.
Feel free to help out ;)

**Comment by persianpros** [comment]
I'm compiling a test version for public and for all models but dm800se gave me max size error and there was no nfi image at last ...

**Comment by persianpros** [comment]
Same with dm500hd

**Comment by persianpros** [comment]
And dm800, So all 3 smallflashes won't work ...

**Comment by Hains** [comment]
We need to get rid of all 'not required things' like kernelwifi, hdmicec,blindscan-dvbc etc.
Besides image, user want to install channel settings and plugins like iptvplayer.

**Comment by persianpros** [comment]
I'm not sure those could fix the problem because the nfi is more than 65mb so some plugins won't do ...

As I do have all 3 in my build I'll start to cleanup.

**Comment by persianpros** [comment]
I think we should consider some MastaG's commits:
https://github.com/MastaG/pli-oe-core/commit/1ef0a3366085cc12fef0fc5bdb7238ffcdbc2686
https://github.com/MastaG/pli-oe-core/commit/0e5d24fe5eae619b108f01259f8ac59a4c5ded98

**Comment by Hains** [comment]
dm800se no problem, image size 56,9 MB out of the box.
