### ISSUE TITLE
libpassthrough support

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#2]
We need to support Dreambox TS/M2TS audio passthrough helper lib but I think we need
```
#check for receiver specific passthrough helper lib
if [ -e @libdir@/libpassthrough.so ]; then
	LIBS="$LIBS @libdir@/libpassthrough.so"
fi
```
in enigma2.sh too which is e2 related.

**Comment by persianpros** [comment]
Also we need to update https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-openwebif.bbappend

**Comment by Hains** [comment]
Indeed. Also for dm8000 in future.This python code doesn't work anymore
```
elif x[0] == 'dm8000':
dir = '%s/public/static/remotes' % pluginpath
os.system('cp %s/dmm1.html %s/dmm.html' % (dir, dir))
--
In latest openembedded-core. os.system is deprecated i have read.on the web.
And openwebif has stupid orgdream check in model branding.
Which result in no full remote control in openwebif. And no brand 'dream multimedia'  in info screen.
Every dm8000 is considered as a clone box in openpli, even your dm8000 is genuine.

Ok, dm8000 is for future addition.
I think there will be need to replace some files in meta-openpli. 
It seems inevitable.

**Comment by persianpros** [comment]
@Hains would you please post your comment here: https://github.com/DMM-PLi/dmm-bsp/issues/4
I did create a new issue for Open WebIF to track everything better :)
