### ISSUE TITLE
Multi tuner problem

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#21]
As discussed here https://github.com/DMM-PLi/meta-dream/issues/14 and here https://forums.openpli.org/topic/55331-test-image-for-dm900/ PLi's enigma2 needs some changes to work with triple tuners and it seems not an easy job ...

For example I think these commits are related to what we want : https://github.com/openatv/enigma2/commit/947f259b6ee6d1b4389f3628896241662bafd4fb
https://github.com/openatv/enigma2/commit/5a643c9a4c0c1e728fabc66eed5d0bad1e36b3f3
https://github.com/openatv/enigma2/commit/a17c84c10a26c211624f9e9f87c101192a8635fd

First we need to list all commits and sources then create a patch for it and maybe we could propose it for PLi's enigma2 later ...

It's not just 1 file and we need to patch so many files ...

**Comment by persianpros** [comment]
It seems vuzero4k uses dvb-s2x too so you could expect PLi do some changes in enigma2 and support dvb-s2x ...

**Comment by Hains** [comment]
@Zeros has ordered a dm900. It's very unclear. According to some users, DVB-S2X works fine for dm900. There is only configuration issue with triple tuner.

Let's wait for @Zeros to confirm. Without having a box, it's really hard.

See also
https://forums.openpli.org/topic/55904-will-pli-be-merging-the-s2x-patch/page-4#entry810856

But you probably seen that thread;) anyway. Yes let's hope OpenPLi are now triggered to support DVB-S2X and perhaps configuration issue SI2169C.

**Comment by persianpros** [comment]
I think we need to wait because PLi will do something about dvb-s2x as they're supporting Vu+ STBs.

**Comment by persianpros** [comment]
Now first one: https://github.com/OpenPLi/enigma2/commit/b078e4bccce6e25421875a7146e5eb508ee5f47c

**Comment by persianpros** [comment]
New drivers for dm9x0 are out which are dvb-s2x related + if you want to test s2x build from rocko branch as it now uses s2x branch of PLi's enigma2.

**Comment by audi06** [comment]
dm9x0
Branch rocko barry allen install error
I did not try flash

**Comment by Hains** [comment]
No support barry allen, try image in flash please.

Which oe-core do you use. openpli-oe-core or pli-oe-core of MastaG?

rocko openpli-oe-core is in development, test etc.
Better to use development branch if you encounter problems.

**Comment by audi06** [comment]
I did not have a chance to try flash
I'm using openpli-oe-core, pli-oe-core uninstall

Which environment should I try for the FBC DVB-Sx2 tuner?
rocko, openpli-oe-core

**Comment by Hains** [comment]
There is no particularly branch for DVB-S2x tuners.
Best branch is 'develop' openpli-oe-core 
As i said, rocko is under development and has some issues.
