### ISSUE TITLE
Backup Suite for dreamboxes

### ISSUE THREAD

**Issue by persianpros** [DMM-PLi/meta-dream#25]
As I said here: https://forums.openpli.org/topic/21460-backupsuite/?view=findpost&p=831620 I want to support dreamboxes with nfi backup, Do we have anybody here could test it?

Sources are here: https://github.com/persianpros/BackupSuite But I didn't push dreamox changes yet ...

**Comment by persianpros** [comment]
Test version: https://forums.openpli.org/topic/21460-backupsuite/?view=findpost&p=831743

**Comment by Hains** [comment]
After restart enigma2 error:

Some plugins are not available
Extensions/BackupSuite (Invalid syntax (plugin.py, line 203))

**Comment by Hains** [comment]
OK a parenthesis too many
```
elif model.startswith("dm"):
```
Creating backup looks good so far.

**Comment by Hains** [comment]
Edit: still not working(sorry wrong backup) now error:

Some plugins are not available:
Extensions/BackupSuite (name'environ' is not defined).

**Comment by Hains** [comment]
Ok i see.. dmm branch ..i'm building now.

**Comment by Hains** [comment]
Now enigma2 doesn't complain anymore about missing files, not defined etc.

But now crashlog:
```
File "/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/plugin.py", line 127, in __init__
    self.skin = skinstartsd
NameError: global name 'skinstartsd' is not defined
```

**Comment by persianpros** [comment]
Sorry dmm branch was not ready but it's ok now: https://github.com/persianpros/BackupSuite/tree/dmm

Build again please :)

Making this plugin for dreamboxes would be nice but as I don't have any enigma2 STB it will be nightmare for me to do it alone

**Comment by persianpros** [comment]
Also it won't work for new xz and bz2 images so don't test it on dm520,dm7080,dm820 and dm900,dm920!

But if we can support these boxes which I believe we can this plugin would be the best for PLi images ;)

https://github.com/OpenPLi/openpli-oe-core/blob/develop/meta-openpli/recipes-openpli/enigma2-plugins/enigma2-plugin-extensions-backupsuite.bb is the bitbake recipe but for dreamboxes we need this:

RDEPENDS_${PN} = "mtd-utils mtd-utils-ubifs ofgwrite mtd-utils-jffs2 dreambox-buildimage"

So can we have another RDEPENDS_${PN} for dreamboxes?

**Comment by Hains** [comment]
I test on dm8000 with UBIFS. I get:
```
df: en_EN can't find mount point

'downloading packages'
mtd-utils is already installed and up to date

pruts/usr/lib/enigma2/python/Plugins/Extensions/BackupSuite/backupdmm.sh: line 210: message02 not found.

Version: git 290

Execution finished!!
```

No backup file;(

**Comment by persianpros** [comment]
Ok test again, I did some changes ...

**Comment by Hains** [comment]
Better now ;)

I have backup file .nfi in automatic_fullbackup on HDD.

Now testing restoring.

**Comment by Hains** [comment]
I have .nfi file in automatic_fulbackup on HDD of 97,3 MB but when i select 'restore backup' backsuite doesn't recognize the .nfi file, it's present but not in the GUI.

**Comment by persianpros** [comment]
Yeah it's ok because Backup Suite can't restore a nfi backup and I don't even know how to do it or is it even possible ... I just wanted to be able to backup nfi images which now it's ok.

Also it won't work for new xz and bz2 images so we can't use it on dm520,dm7080,dm820 and dm900,dm920 which I like to fix this at least for bz2 images (dm900 and dm920).

**Comment by Hains** [comment]
Yes creating a backup file is a great feature. Restore image with web interface is OK,
Thanks. 

Indeed it would be great indeed to add dm900 and dm920.

**Comment by persianpros** [comment]
So there is no way to flash a nfi image within an installed one? Like what we do with ofgwrite I mean.

**Comment by Hains** [comment]
No that's not possible at the moment. I can't select an .nfi file, so i have to do with the old way.
ofgwrite is not for dreamboxes AFAIK.

**Comment by persianpros** [comment]
Ok now please help me with xz and bz2:

dm520,dm7080,dm820 are using xz but what are the steps to produce it so I can add it to Backup Suite?

dm900 and dm920 are using bz2, Is the same like other STBs for example vuultimo4k?

**Comment by Hains** [comment]
I had to dive deep into backupsuite to help you.
When i have some time left, i'll give it a try.
And i have dm8000 only.
But @Zeros has dm920, i can ask him to test.

**Comment by persianpros** [comment]
Ok please be online, I want you test the new version with old and dm9x0 support (xz not yet).

If you can tell @ZeroS to test dm9x0 version please do that too :)

**Comment by Hains** [comment]
Done, send PM to him.
Now wait.

**Comment by persianpros** [comment]
Please build and test again now :)

**Comment by persianpros** [comment]
Thanks for the test, Please build and test again now.

**Comment by Hains** [comment]
At the end it fails.. i lost error, i run backup again.
The estimated time is lost now(although cosmetic). With previous commit it was 6 minutes(which seems to be correct). 
Now:
```
Please be patient, a backup will now be made, this will take about: ash invaiid numer, 0 ash invalid number 00 minutes.

Second try:
Mount. Mounting /dev/mtdbloack/2 on /tmp/bi/boot failed, cannot allocate memory.
```

I have to wait till backup is finished, reboot the box and try again.

**Comment by Hains** [comment]
backupdmm.sh: line 868 aritmetic syntac error.

**Comment by persianpros** [comment]
Ok wait please ...

**Comment by persianpros** [comment]
Please build and test again.

**Comment by Hains** [comment]
line 694

**Comment by persianpros** [comment]
Please build and test again.

**Comment by persianpros** [comment]
Please build and test again. I just added situations.

**Comment by Hains** [comment]
Now OK again without errors.

**Comment by persianpros** [comment]
Please build and test again. I just added situations.

**Comment by Hains** [comment]
Last commit OK.

**Comment by Hains** [comment]
Oh euh Zeros is username OpenPLi forum. Github account is 
https://github.com/UrmasP

Just to be clear.

**Comment by persianpros** [comment]
Thanks a lot my friend :)

I did some cleanups here and deleted the comments that we took care of.

So now the status is:

1- All old dreamboxes with "nfi" images could create backup but restore is not possible via Backup Suite itself as we have to flash them via DMM's webif.

2- dm9x0 backup/restore not tested yet ...

3- dm520,dm7080,dm820 with xz images not yet supported ...

**Comment by Hains** [comment]
I know someone with a dm7080. I can ask him to test.

**Comment by persianpros** [comment]
That's good but first I need to find a way to support xz images :(

**Comment by persianpros** [comment]
For dm9x0 we have:
KERNEL_FILE = "kernel.bin"
ROOTFS_FILE = "rootfs.tar.bz2"
But what about dm52x,dm7080,dm820? Is it
KERNEL_FILE = "kernel.bin"
ROOTFS_FILE = "rootfs.tar.xz"
?

**Comment by persianpros** [comment]
@Hains would you please inform your friend with dm7080 to test the new version of the plugin for xz backup as I did some changes regarding it?

**Comment by persianpros** [comment]
I did some changes on backupsuite so compile and test again: https://github.com/persianpros/BackupSuite/commits/master

**Comment by Hains** [comment]
Which new OE core, machine needs to be added to dvb-modules. See
https://github.com/Hains/BackupSuite/commit/033927e9f9ae9adfcfc8a0e0bc17f1a820484ba1
and
https://github.com/Hains/BackupSuite/commit/12166ab112f75ac9efe39f1002e2466bed9be3f4

Otherwise No supported receiver found! .

**Comment by audi06** [comment]
dbackup no problem, it works nicely...

**Comment by persianpros** [comment]
@Hains Can you help me with this new error my friend?
https://forums.openpli.org/topic/21460-backupsuite/?view=findpost&p=838829
As I don't have any e2 stb I can't test it but dreambox users with develop were ok ...

**Comment by Hains** [comment]
I have my doubt about post #932 as it seems user hasn't the latest plugin.py. See line 105 and line 236 old and new plugin.py.

I can only check backup to USB instead of HDD. I'll do that this morning.
